<?php

namespace RMSArdra\Bundle\RMSBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobRequirementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRequirementRepository extends EntityRepository
{
}
